language: go

os:
  - windows
  - linux
  - osx

go:
  - "1.11.x"

env:
  - CONTEXT=abs

script: 
 - go test ./... -vet=off -v -covermode=count -coverprofile=coverage.out
 - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out