language: go

os:
  - windows
  - linux
  - osx

go:
  - "1.12.x"

before_script:
- go get -u 
- go get github.com/mattn/goveralls

env:
    global: 
        - GO111MODULE=on
  - CONTEXT=abs

script: 
 - GO111MODULE=on go test `go list ./... | grep -v "/js"` -vet=off -v -covermode=count -coverprofile=coverage.out
 - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out
